"""add_orchestrator_tables

Revision ID: de942d2cc5d0
Revises: 7574c14f57cf
Create Date: 2026-01-27 07:15:39.613214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de942d2cc5d0'
down_revision: Union[str, Sequence[str], None] = '7574c14f57cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('orchestrator_approved', sa.Boolean(), nullable=True))
    op.add_column('stages', sa.Column('orchestrator_score', sa.Float(), nullable=True))
    op.add_column('stages', sa.Column('orchestrator_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'orchestrator_feedback')
    op.drop_column('stages', 'orchestrator_score')
    op.drop_column('stages', 'orchestrator_approved')
    # ### end Alembic commands ###
